version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/" # or wherever your .csproj/.sln file is
    schedule:
      interval: "weekly" # or "daily", "monthly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
