##
## Copyright 2021-23 Williams Technologies Limited.
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
## Kajabity is a trademark of Williams Technologies Limited.
##
## http://www.kajabity.com
##

#---------------------------------# 
#      general configuration      # 
#---------------------------------# 

# Set build image: needs to include MSBuild 15.0 or higher
image: Visual Studio 2022
 
# version format 
#version: {build}

# branches to build
#branches

 
# Do not build on tags (GitHub only)
# This avoids the infinite build loop as Deploy to GitHub is set to create a tag each time.
skip_tags: true 

#---------------------------------# 
#    environment configuration    # 
#---------------------------------# 
 
# scripts that are called at very beginning, before repo cloning 
init:
- git config --global core.autocrlf true

# Automatically register private account and/or project AppVeyor NuGet feeds.
nuget:
    account_feed: true
    project_feed: true
    disable_publish_on_pr: true     # disable publishing of .nupkg artifacts to
                                    # account/project feeds for pull request builds

#---------------------------------# 
#       build configuration       # 
#---------------------------------# 
 
# build platform, i.e. x86, x64, Any CPU. This setting is optional. 
# platform:

before_build:
    - cmd: dotnet restore "Kajabity.Demo.sln"

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

build:
    publish_nuget: true             # package projects with .nuspec files and push to artifacts 
    publish_nuget_symbols: true     # generate and publish NuGet symbol packages
    include_nuget_references: false # add -IncludeReferencedProjects option while packaging NuGet artifacts
        # *** Now set to false due to following warning:
        #   Separate packages per project and P2P references are recommended. More info: https://github.com/dotnet/cli/issues/3959
        #   Therefore 'Include referenced projects' setting is ignored for .NET Core or .NET Standard projects.
        #   dotnet

# MSBuild verbosity level - one of quiet|minimal|normal|detailed
    verbosity: normal

#---------------------------------# 
#      artifacts configuration    # 
#---------------------------------# 

# Artifacts picked up by nuget deployment and includes all DLL variants for each .NET version.
#artifacts:
#    - path: Kajabity.Demo\bin\$(configuration)\Kajabity.Demo.dll

#---------------------------------# 
#     deployment configuration    # 
#---------------------------------# 

# providers: Local, FTP, WebDeploy, AzureCS, AzureBlob, S3, NuGet, Environment 
# provider names are case-sensitive! 

deploy:
    # Secure tokens created using https://ci.appveyor.com/tools/encrypt

    # Deploying to NuGet feed - using API Key from NuGet.org.
  - provider: NuGet
    api_key:
        secure: QWofWYdsyI6kea9misqm/juAxauOznkiITnk5BT8WUaqQPKQwAeW9WpD/zt/5gVP
    skip_symbols: true
    artifact: /.*\.nupkg/
    on:
        #appveyor_repo_tag: true        # deploy on tag push only - removed or won't deploy at all.
        branch: main                    # release from main branch only

    # Deploy to GitHub Releases 
  - provider: GitHub 
    release: $(MinVerVersion)
    description: 'Kajabity.Demo Release v$(MinVerVersion)'
    auth_token:
        secure: JcFMulBQj5uHDMqqyRApmJbzVa5hj5US8+hZ85ybBgAxLTYhGLxSTckqokhDybA+
    draft: false
    prerelease: false
    #appveyor_repo_tag: true        # deploy on tag push only
