name: Scheduled Dependency Check

on:
  schedule:
    - cron: '0 3 * * 5' # Runs every Friday at 3 AM (UTC)

jobs:
  dependency-check:
    name: Dependency Updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check Dependencies
        uses: JoranHarmse/nuget-outdated-action@v1.0