name: Scheduled Vulnerability Check

on:
  schedule:
    - cron: '0 0 * * 5' # Runs every Friday at midnight (UTC)

jobs:
  security-check:
    name: Security Vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Security Scan
        uses: aquasecurity/trivy-action@v0.12
        with:
          scan-type: filesystem
          format: table